# EXTRACT

In [1]:
import pandas as pd

df_mortality = pd.read_csv(r'C:\Users\LUCKY SURYA\Documents\kuliah\semester 4\data warehouse\UAS\dataset 4\mortality\mortality.csv')
df_life_expectancy = pd.read_csv(r'C:\Users\LUCKY SURYA\Documents\kuliah\semester 4\data warehouse\UAS\dataset 4\life expentancy\life_expentancy.csv')
df_cause_of_death = pd.read_csv(r'C:\Users\LUCKY SURYA\Documents\kuliah\semester 4\data warehouse\UAS\dataset 4\cause of death\penyebab_kematian.csv')
df_income_level = pd.read_csv(r'C:\Users\LUCKY SURYA\Documents\kuliah\semester 4\data warehouse\UAS\dataset 4\income level\income_level_per_region.csv')
df_population = pd.read_csv(r'C:\Users\LUCKY SURYA\Documents\kuliah\semester 4\data warehouse\UAS\dataset 4\population\population.csv')

print(f"Mortality : {len(df_mortality)} baris, {df_mortality.shape[1]} kolom")
print(f"Life Expectancy : {len(df_life_expectancy)} baris, {df_life_expectancy.shape[1]} kolom")
print(f"Cause of Death : {len(df_cause_of_death)} baris, {df_cause_of_death.shape[1]} kolom")
print(f"Income Level : {len(df_income_level)} baris, {df_income_level.shape[1]} kolom")
print(f"Population : {len(df_population)} baris, {df_population.shape[1]} kolom")

Mortality : 266 baris, 71 kolom
Life Expectancy : 266 baris, 71 kolom
Cause of Death : 899540 baris, 6 kolom
Income Level : 17556 baris, 5 kolom
Population : 266 baris, 71 kolom

In [2]:
print('mortality :')
df_mortality.head(10)

mortality :

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,47.002258,44.463549,43.349158,42.850093,44.321233,44.341994,41.969085,40.688856,NaN,NaN
2,Afghanistan,AFG,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,252.4,249.2,246.4,243.6,240.6,237.7,...,60.100000,58.300000,56.600000,54.900000,53.200000,51.600000,49.900000,48.300000,NaN,NaN
3,Africa Western and Central,AFW,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.089852,60.383223,60.635951,59.321798,59.132592,60.096106,57.353682,56.462511,NaN,NaN
4,Angola,AGO,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.700000,36.000000,35.500000,34.900000,34.400000,33.700000,33.000000,32.100000,NaN,NaN
5,Albania,ALB,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.700000,7.800000,8.000000,8.100000,8.300000,8.300000,8.300000,8.300000,NaN,NaN
6,Andorra,AND,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.100000,3.000000,2.900000,2.800000,2.700000,2.600000,2.500000,2.400000,NaN,NaN
7,Arab World,ARB,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.583542,29.788790,28.866042,28.304839,27.882491,28.727005,27.440937,26.584268,NaN,NaN
8,United Arab Emirates,ARE,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,146.3,139.2,132.2,125.0,117.5,109.9,...,5.600000,5.300000,5.000000,4.700000,4.400000,4.200000,4.000000,3.800000,NaN,NaN
9,Argentina,ARG,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.400000,9.100000,8.900000,8.700000,8.500000,8.400000,8.200000,8.000000,NaN,NaN

In [3]:
df_mortality = df_mortality[['Country Code','Country Name','Indicator Name','Indicator Code','2017','2018','2019','2020']].rename(columns={'Country Code': 'kode_negara', 'Country Name': 'negara', 'Indicator Name': 'nama_indikator', 'Indicator Code': 'kode_indikator'}).copy()
df_mortality.head(10)

,kode_negara,negara,nama_indikator,kode_indikator,2017,2018,2019,2020
0,ABW,Aruba,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,NaN,NaN,NaN,NaN
1,AFE,Africa Eastern and Southern,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,47.002258,44.463549,43.349158,42.850093
2,AFG,Afghanistan,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,60.100000,58.300000,56.600000,54.900000
3,AFW,Africa Western and Central,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,61.089852,60.383223,60.635951,59.321798
4,AGO,Angola,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,36.700000,36.000000,35.500000,34.900000
5,ALB,Albania,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,7.700000,7.800000,8.000000,8.100000
6,AND,Andorra,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,3.100000,3.000000,2.900000,2.800000
7,ARB,Arab World,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,30.583542,29.788790,28.866042,28.304839
8,ARE,United Arab Emirates,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,5.600000,5.300000,5.000000,4.700000
9,ARG,Argentina,"Mortality rate, infant (per 1,000 live births)",SP.DYN.IMRT.IN,9.400000,9.100000,8.900000,8.700000

In [4]:
print('life expectancy :')
df_life_expectancy.head(10)

life expectancy :

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,64.049000,64.215000,64.602000,64.944000,65.303000,65.615000,...,75.620000,75.880000,76.019000,75.406000,73.655000,76.226000,76.353000,76.500000,NaN,NaN
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,44.169658,44.468838,44.877890,45.160583,45.535695,45.770723,...,62.591275,63.330691,63.857261,63.766484,62.979999,64.487152,65.146228,65.349930,NaN,NaN
2,Afghanistan,AFG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,32.799000,33.291000,33.757000,34.201000,34.673000,35.124000,...,62.406000,62.443000,62.941000,61.454000,60.417000,65.617000,66.035000,66.289000,NaN,NaN
3,Africa Western and Central,AFW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.779636,38.058973,38.681792,38.936918,39.194580,39.479784,...,56.626622,57.037104,57.149956,57.364736,57.362736,57.987850,58.855740,59.049811,NaN,NaN
4,Angola,AGO,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.933000,36.902000,37.168000,37.419000,37.704000,37.968000,...,62.122000,62.622000,63.051000,63.116000,62.958000,64.246000,64.617000,64.805000,NaN,NaN
5,Albania,ALB,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,56.413000,57.488000,58.494000,59.479000,60.404000,61.273000,...,78.900000,79.238000,79.467000,77.824000,76.844000,78.769000,79.602000,79.776000,NaN,NaN
6,Andorra,AND,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,72.094000,72.573000,72.993000,73.298000,73.624000,73.856000,...,84.359000,84.242000,84.098000,79.418000,82.331000,84.016000,84.041000,84.188000,NaN,NaN
7,Arab World,ARB,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,44.794056,45.545371,45.993769,46.979338,47.570034,48.117159,...,71.112856,71.431300,71.839893,70.726559,70.404114,71.876096,72.444678,72.721805,NaN,NaN
8,United Arab Emirates,ARE,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,50.651000,51.596000,52.546000,53.509000,54.495000,55.512000,...,82.388000,82.449000,82.596000,81.936000,79.083000,80.487000,82.909000,83.069000,NaN,NaN
9,Argentina,ARG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,64.242000,64.631000,64.618000,64.855000,64.816000,65.053000,...,76.543000,76.770000,76.847000,75.878000,73.948000,75.806000,77.395000,77.543000,NaN,NaN

In [5]:
df_life_expectancy =df_life_expectancy[['Country Code','Country Name','Indicator Name','Indicator Code','2017','2018','2019','2020']].rename(columns={'Country Code': 'kode_negara', 'Country Name': 'negara', 'Indicator Name': 'nama_indikator', 'Indicator Code': 'kode_indikator'}).copy()
df_life_expectancy.head(10)

,kode_negara,negara,nama_indikator,kode_indikator,2017,2018,2019,2020
0,ABW,Aruba,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,75.620000,75.880000,76.019000,75.406000
1,AFE,Africa Eastern and Southern,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,62.591275,63.330691,63.857261,63.766484
2,AFG,Afghanistan,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,62.406000,62.443000,62.941000,61.454000
3,AFW,Africa Western and Central,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,56.626622,57.037104,57.149956,57.364736
4,AGO,Angola,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,62.122000,62.622000,63.051000,63.116000
5,ALB,Albania,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,78.900000,79.238000,79.467000,77.824000
6,AND,Andorra,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,84.359000,84.242000,84.098000,79.418000
7,ARB,Arab World,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,71.112856,71.431300,71.839893,70.726559
8,ARE,United Arab Emirates,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,82.388000,82.449000,82.596000,81.936000
9,ARG,Argentina,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,76.543000,76.770000,76.847000,75.878000

In [6]:
print('cause of death :')
df_cause_of_death['negara'] = df_cause_of_death['negara'].str.capitalize().copy()
df_cause_of_death.head(10)

cause of death :

,negara,tahun,penyebab_kematian,jenis_kelamin,kelompok_umur,jumlah_kematian
0,Seychelles,2017,All causes,pria,0-65+ tahun (Sangat Kurang Mendetail),429
1,Seychelles,2017,All causes,wanita,0-65+ tahun (Sangat Kurang Mendetail),325
2,Seychelles,2017,Certain infectious and parasitic diseases,pria,0-65+ tahun (Sangat Kurang Mendetail),22
3,Seychelles,2017,Certain infectious and parasitic diseases,wanita,0-65+ tahun (Sangat Kurang Mendetail),25
4,Seychelles,2017,Cholera,pria,0-65+ tahun (Sangat Kurang Mendetail),0
5,Seychelles,2017,Cholera,wanita,0-65+ tahun (Sangat Kurang Mendetail),0
6,Seychelles,2017,Diarrhoea and gastroenteritis of presumed infe...,pria,0-65+ tahun (Sangat Kurang Mendetail),1
7,Seychelles,2017,Diarrhoea and gastroenteritis of presumed infe...,wanita,0-65+ tahun (Sangat Kurang Mendetail),1
8,Seychelles,2017,Other intestinal infectious diseases,pria,0-65+ tahun (Sangat Kurang Mendetail),0
9,Seychelles,2017,Other intestinal infectious diseases,wanita,0-65+ tahun (Sangat Kurang Mendetail),0

In [7]:
print('income level :')
df_income_level.head(10)

income level :

  country_code  year  gdp_per_capita                      country income_level
0          AFE  2025             NaN  Africa Eastern and Southern   Aggregates
1          AFE  2024     1615.396356  Africa Eastern and Southern   Aggregates
2          AFE  2023     1571.449189  Africa Eastern and Southern   Aggregates
3          AFE  2022     1679.327622  Africa Eastern and Southern   Aggregates
4          AFE  2021     1562.416175  Africa Eastern and Southern   Aggregates
5          AFE  2020     1351.591669  Africa Eastern and Southern   Aggregates
6          AFE  2019     1507.085600  Africa Eastern and Southern   Aggregates
7          AFE  2018     1552.073722  Africa Eastern and Southern   Aggregates
8          AFE  2017     1528.104224  Africa Eastern and Southern   Aggregates
9          AFE  2016     1334.470500  Africa Eastern and Southern   Aggregates

In [8]:
df_income_level = df_income_level[df_income_level['year'].between(2017, 2020)].reset_index(drop=True).rename(columns={'country_code': 'kode_negara', 'year': 'tahun','country' : 'negara','income_level': 'level_pendapatan'}).copy()
df_income_level.head(10)

,kode_negara,tahun,gdp_per_capita,negara,level_pendapatan
0,AFE,2020,1351.591669,Africa Eastern and Southern,Aggregates
1,AFE,2019,1507.085600,Africa Eastern and Southern,Aggregates
2,AFE,2018,1552.073722,Africa Eastern and Southern,Aggregates
3,AFE,2017,1528.104224,Africa Eastern and Southern,Aggregates
4,AFW,2020,2030.861659,Africa Western and Central,Aggregates
5,AFW,2019,2216.385055,Africa Western and Central,Aggregates
6,AFW,2018,1720.140092,Africa Western and Central,Aggregates
7,AFW,2017,1574.230564,Africa Western and Central,Aggregates
8,ARB,2020,5739.412836,Arab World,Aggregates
9,ARB,2019,6674.342244,Arab World,Aggregates

In [9]:
print('population :')
df_population.head(10)

population :

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN
5,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2648285.0,2607733.0,2567801.0,2528480.0,2489762.0,2451636.0,2414095.0,2377128.0,NaN,NaN
6,Andorra,AND,"Population, total",SP.POP.TOTL,9510.0,10283.0,11086.0,11915.0,12764.0,13634.0,...,73763.0,75162.0,76474.0,77380.0,78364.0,79705.0,80856.0,81938.0,NaN,NaN
7,Arab World,ARB,"Population, total",SP.POP.TOTL,91540853.0,93931683.0,96428599.0,99038509.0,101729760.0,104494008.0,...,428315886.0,435998060.0,444281315.0,453723239.0,460646603.0,471352066.0,482105978.0,492612632.0,NaN,NaN
8,United Arab Emirates,ARE,"Population, total",SP.POP.TOTL,131334.0,137989.0,144946.0,152211.0,159692.0,167103.0,...,9223225.0,9346701.0,9445785.0,9401038.0,9575152.0,10074977.0,10483751.0,10986400.0,NaN,NaN
9,Argentina,ARG,"Population, total",SP.POP.TOTL,20386045.0,20726276.0,21072538.0,21421705.0,21769453.0,22112629.0,...,44288894.0,44654882.0,44973465.0,45191965.0,45312281.0,45407904.0,45538401.0,45696159.0,NaN,NaN

In [10]:
df_population =df_population[['Country Code','Country Name','Indicator Name','Indicator Code','2017','2018','2019','2020']].rename(columns={'Country Code': 'kode_negara', 'Country Name': 'negara', 'Indicator Name': 'nama_indikator', 'Indicator Code': 'kode_indikator'}).copy()
df_population.head(10)

,kode_negara,negara,nama_indikator,kode_indikator,2017,2018,2019,2020
0,ABW,Aruba,"Population, total",SP.POP.TOTL,108735.0,108908.0,109203.0,108587.0
1,AFE,Africa Eastern and Southern,"Population, total",SP.POP.TOTL,640058741.0,657801085.0,675950189.0,694446100.0
2,AFG,Afghanistan,"Population, total",SP.POP.TOTL,35688935.0,36743039.0,37856121.0,39068979.0
3,AFW,Africa Western and Central,"Population, total",SP.POP.TOTL,440882906.0,452195915.0,463365429.0,474569351.0
4,AGO,Angola,"Population, total",SP.POP.TOTL,30234839.0,31297155.0,32375632.0,33451132.0
5,ALB,Albania,"Population, total",SP.POP.TOTL,2648285.0,2607733.0,2567801.0,2528480.0
6,AND,Andorra,"Population, total",SP.POP.TOTL,73763.0,75162.0,76474.0,77380.0
7,ARB,Arab World,"Population, total",SP.POP.TOTL,428315886.0,435998060.0,444281315.0,453723239.0
8,ARE,United Arab Emirates,"Population, total",SP.POP.TOTL,9223225.0,9346701.0,9445785.0,9401038.0
9,ARG,Argentina,"Population, total",SP.POP.TOTL,44288894.0,44654882.0,44973465.0,45191965.0

## Cek data

In [11]:
print("Nilai kosong:")
print("\nmortality:")
print(df_mortality.isnull().sum())
print("\nlife expectancy:")
print(df_life_expectancy.isnull().sum())

Nilai kosong:

mortality:
kode_negara        0
negara             0
nama_indikator     0
kode_indikator     0
2017              22
2018              22
2019              22
2020              22
dtype: int64

life expectancy:
kode_negara       0
negara            0
nama_indikator    0
kode_indikator    0
2017              1
2018              1
2019              1
2020              1
dtype: int64

In [12]:
print("\ncause of death:")
print(df_cause_of_death.isnull().sum())
print("\nincome level:")
print(df_income_level.isnull().sum())
print("\npopulation:")
print(df_population.isnull().sum())

cause of death:
negara               0
tahun                0
penyebab_kematian    0
jenis_kelamin        0
kelompok_umur        0
jumlah_kematian      0
dtype: int64

income level:
kode_negara         20
tahun                0
gdp_per_capita      29
negara              20
level_pendapatan    20
dtype: int64

population:
kode_negara       0
negara            0
nama_indikator    0
kode_indikator    0
2017              1
2018              1
2019              1
2020              1
dtype: int64

In [13]:
print("Duplikat:")
dup_count = df_mortality.duplicated(subset=['kode_negara']).sum()
print(f"Jumlah kode_negara duplikat: {dup_count}")
df_mortality[df_mortality.duplicated(subset=["kode_negara"], keep=False)].sort_values("kode_negara").head(6)

Duplikat:
Jumlah kode_negara duplikat: 0

Empty DataFrame
Columns: [kode_negara, negara, nama_indikator, kode_indikator, 2017, 2018, 2019, 2020]
Index: []

In [14]:
print("Duplikat:")
dup_count = df_life_expectancy.duplicated(subset=['kode_negara']).sum()
print(f"Jumlah kode_negara duplikat: {dup_count}")
df_life_expectancy[df_life_expectancy.duplicated(subset=["kode_negara"], keep=False)].sort_values("kode_negara").head(6)

Duplikat:
Jumlah kode_negara duplikat: 0

Empty DataFrame
Columns: [kode_negara, negara, nama_indikator, kode_indikator, 2017, 2018, 2019, 2020]
Index: []

In [15]:
print("Duplikat:")
dup_count = df_population.duplicated(subset=['kode_negara']).sum()
print(f"Jumlah kode_negara duplikat: {dup_count}")
df_population[df_population.duplicated(subset=["kode_negara"], keep=False)].sort_values("kode_negara").head(6)

Duplikat:
Jumlah kode_negara duplikat: 0

Empty DataFrame
Columns: [kode_negara, negara, nama_indikator, kode_indikator, 2017, 2018, 2019, 2020]
Index: []

In [16]:
print("Unik kode_negara (mortality):")
print(sorted(df_mortality["kode_negara"].unique()))

print("\nUnik negara (mortality):")
print(sorted(df_mortality["negara"].unique()))

print("\nUnik kode_indikator (mortality):")
print(sorted(df_mortality["kode_indikator"].unique()))

print("\nUnik nama_indikator (mortality):")
print(sorted(df_mortality["nama_indikator"].unique()))

Unik kode_negara (mortality):
['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG', 'ARM', 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CEB', 'CHE', 'CHI', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL', 'COM', 'CPV', 'CRI', 'CSS', 'CUB', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'ECU', 'EGY', 'EMU', 'ERI', 'ESP', 'EST', 'ETH', 'EUU', 'FCS', 'FIN', 'FJI', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GHA', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HIC', 'HKG', 'HND', 'HPC', 'HRV', 'HTI', 'HUN', 'IBD', 'IBT', 'IDA', 'IDB', 'IDN', 'IDX', 'IMN', 'IND', 'INX', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAC', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LCN', 'LDC', 'LIC', 'LIE', 'LKA', 'LMC', 'LMY', 'LSO', 'LTE', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEA', 'MEX', 'MHL', 'MIC', 'MKD', 'MLI', 'MLT', 'MMR', 'MNA', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAC', 'NAM', 'NCL', 'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OED', 'OMN', 'OSS', 'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRE', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PSS', 'PST', 'PYF', 'QAT', 'ROU', 'RUS', 'RWA', 'SAS', 'SAU', 'SDN', 'SEN', 'SGP', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SRB', 'SSA', 'SSD', 'SSF', 'SST', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TEA', 'TEC', 'TGO', 'THA', 'TJK', 'TKM', 'TLA', 'TLS', 'TMN', 'TON', 'TSA', 'TSS', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA', 'UKR', 'UMC', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLD', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE']

Unik negara (mortality):
['Afghanistan', 'Africa Eastern and Southern', 'Africa Western and Central', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD countries)', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend', 'Latin America & Caribbean', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia', 'Least developed countries: UN classification', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low & middle income', 'Low income', 'Lower middle income', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Middle East, North Africa, Afghanistan & Pakistan', 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)', 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)', 'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Not classified', 'OECD members', 'Oman', 'Other small states', 'Pacific island small states', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Post-demographic dividend', 'Pre-demographic dividend', 'Puerto Rico (US)', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia', 'Small states', 'Solomon Islands', 'Somalia, Fed. Rep.', 'South Africa', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Martin (French part)', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

Unik kode_indikator (mortality):
['SP.DYN.IMRT.IN']

Unik nama_indikator (mortality):
['Mortality rate, infant (per 1,000 live births)']

In [17]:
print("Unik kode_negara (life_expectancy):")
print(sorted(df_life_expectancy["kode_negara"].unique()))

print("\nUnik negara (life_expectancy):")
print(sorted(df_life_expectancy ["negara"].unique()))

print("\nUnik kode_indikator (life_expectancy):")
print(sorted(df_life_expectancy["kode_indikator"].unique()))

print("\nUnik nama_indikator (life_expectancy):")
print(sorted(df_life_expectancy["nama_indikator"].unique()))

Unik kode_negara (life_expectancy):
['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG', 'ARM', 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CEB', 'CHE', 'CHI', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL', 'COM', 'CPV', 'CRI', 'CSS', 'CUB', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'ECU', 'EGY', 'EMU', 'ERI', 'ESP', 'EST', 'ETH', 'EUU', 'FCS', 'FIN', 'FJI', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GHA', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HIC', 'HKG', 'HND', 'HPC', 'HRV', 'HTI', 'HUN', 'IBD', 'IBT', 'IDA', 'IDB', 'IDN', 'IDX', 'IMN', 'IND', 'INX', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAC', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LCN', 'LDC', 'LIC', 'LIE', 'LKA', 'LMC', 'LMY', 'LSO', 'LTE', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEA', 'MEX', 'MHL', 'MIC', 'MKD', 'MLI', 'MLT', 'MMR', 'MNA', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAC', 'NAM', 'NCL', 'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OED', 'OMN', 'OSS', 'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRE', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PSS', 'PST', 'PYF', 'QAT', 'ROU', 'RUS', 'RWA', 'SAS', 'SAU', 'SDN', 'SEN', 'SGP', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SRB', 'SSA', 'SSD', 'SSF', 'SST', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TEA', 'TEC', 'TGO', 'THA', 'TJK', 'TKM', 'TLA', 'TLS', 'TMN', 'TON', 'TSA', 'TSS', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA', 'UKR', 'UMC', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLD', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE']

Unik negara (life_expectancy):
['Afghanistan', 'Africa Eastern and Southern', 'Africa Western and Central', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD countries)', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend', 'Latin America & Caribbean', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia', 'Least developed countries: UN classification', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low & middle income', 'Low income', 'Lower middle income', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Middle East, North Africa, Afghanistan & Pakistan', 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)', 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)', 'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Not classified', 'OECD members', 'Oman', 'Other small states', 'Pacific island small states', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Post-demographic dividend', 'Pre-demographic dividend', 'Puerto Rico (US)', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia', 'Small states', 'Solomon Islands', 'Somalia, Fed. Rep.', 'South Africa', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Martin (French part)', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

Unik kode_indikator (life_expectancy):
['SP.DYN.LE00.IN']

Unik nama_indikator (life_expectancy):
['Life expectancy at birth, total (years)']

In [18]:
print("Unik negara (penyebab_kematian):")
print(sorted(df_cause_of_death["negara"].unique()))

print("\nUnik penyebab (penyebab_kematian):")
print(sorted(df_cause_of_death["penyebab_kematian"].unique()))

print("\nUnik jenis_kelamin:")
print(sorted(df_cause_of_death["jenis_kelamin"].unique()))

Unik negara (penyebab_kematian):
['Afrika selatan', 'Albania', 'Amerika serikat', 'Andorra', 'Anguilla', 'Antigua dan barbuda', 'Antilen belanda', 'Arab saudi', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Belanda', 'Belarus', 'Belgia', 'Bermuda', 'Bolivia', 'Bosnia dan herzegovina', 'Brasil', 'Britania raya', 'Brunei darussalam', 'Bulgaria', 'Ceko', 'Cile', 'Denmark', 'Dominika', 'Ekuador', 'El salvador', 'Estonia', 'Fiji', 'Filipina', 'Finlandia', 'Georgia', 'Gibraltar', 'Grenada', 'Guadeloupe', 'Guatemala', 'Guyana', 'Guyana prancis', 'Haiti', 'Honduras', 'Hong kong (cina)', 'Hongaria', 'Irak', 'Iran', 'Irlandia', 'Islandia', 'Italia', 'Jepang', 'Jerman', 'Kazakhstan', 'Kepulauan cayman', 'Kepulauan turks dan caicos', 'Kirgizstan', 'Kolombia', 'Korea selatan', 'Kosta rika', 'Kroasia', 'Kuba', 'Kuwait', 'Latvia', 'Lituania', 'Luksemburg', 'Makedonia utara', 'Maladewa', 'Malaysia', 'Malta', 'Maroko', 'Martinique', 'Mauritius', 'Meksiko', 'Mesir', 'Moldova', 'Monako', 'Mongolia', 'Montenegro', 'Montserrat', 'Mozambik', 'Nikaragua', 'Norwegia', 'Oman', 'Panama', 'Paraguay', 'Peru', 'Polandia', 'Portugal', 'Prancis', 'Puerto rico', 'Qatar', 'Republik dominika', 'Reunion', 'Rumania', 'Rusia', 'Saint kitts dan nevis', 'Saint vincent dan grenadines', 'Samoa', 'San marino', 'Santa lusia', 'Sao tome dan principe', 'Selandia baru', 'Senegal', 'Serbia', 'Serbia dan montenegro', 'Seychelles', 'Siprus', 'Slovakia', 'Spanyol', 'Suriname', 'Swedia', 'Swiss', 'Tajikistan', 'Trinidad dan tobago', 'Turki', 'Turkmenistan', 'Tuvalu', 'Ukraina', 'Uruguay', 'Uzbekistan', 'Wallis dan futuna', 'Yordania', 'Yunani', 'Zimbabwe']

Unik penyebab (penyebab_kematian):

In [19]:
print("Unik kode_negara (income_level):")
print(sorted(df_income_level["kode_negara"].astype(str).unique()))

print("\nUnik negara (income_level):")
print(sorted(df_income_level["negara"].astype(str).unique()))

print("\nUnik level_pendapatan:")
print(sorted(df_income_level["level_pendapatan"].astype(str).unique()))

Unik kode_negara (income_level):
['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG', 'ARM', 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CEB', 'CHE', 'CHI', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL', 'COM', 'CPV', 'CRI', 'CSS', 'CUB', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'ECU', 'EGY', 'EMU', 'ERI', 'ESP', 'EST', 'ETH', 'EUU', 'FCS', 'FIN', 'FJI', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GHA', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HKG', 'HND', 'HPC', 'HRV', 'HTI', 'HUN', 'IBD', 'IBT', 'IDA', 'IDB', 'IDN', 'IDX', 'IMN', 'IND', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAC', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LCN', 'LDC', 'LIE', 'LKA', 'LMY', 'LSO', 'LTE', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEA', 'MEX', 'MHL', 'MIC', 'MKD', 'MLI', 'MLT', 'MMR', 'MNA', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAC', 'NAM', 'NCL', 'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OED', 'OMN', 'OSS', 'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRE', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PSS', 'PST', 'PYF', 'QAT', 'ROU', 'RUS', 'RWA', 'SAS', 'SAU', 'SDN', 'SEN', 'SGP', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SRB', 'SSA', 'SSD', 'SSF', 'SST', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TEA', 'TEC', 'TGO', 'THA', 'TJK', 'TKM', 'TLA', 'TLS', 'TMN', 'TON', 'TSA', 'TSS', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA', 'UKR', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLD', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE', 'nan']

Unik negara (income_level):
['Afghanistan', 'Africa Eastern and Southern', 'Africa Western and Central', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD countries)', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend', 'Latin America & Caribbean ', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia', 'Least developed countries: UN classification', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low & middle income', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Middle East, North Africa, Afghanistan & Pakistan', 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)', 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)', 'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'OECD members', 'Oman', 'Other small states', 'Pacific island small states', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Post-demographic dividend', 'Pre-demographic dividend', 'Puerto Rico (US)', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia', 'Small states', 'Solomon Islands', 'Somalia, Fed. Rep.', 'South Africa', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Martin (French part)', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa ', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe', 'nan']

Unik level_pendapatan:
['Aggregates', 'High income', 'Low income', 'Lower middle income', 'Not classified', 'Upper middle income', 'nan']

In [20]:
print("Unik kode_negara (population):")
print(sorted(df_population["kode_negara"].astype(str).unique()))

print("\nUnik negara (population):")
print(sorted(df_population["negara"].astype(str).unique()))

Unik kode_negara (population):
['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG', 'ARM', 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CEB', 'CHE', 'CHI', 'CHL', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL', 'COM', 'CPV', 'CRI', 'CSS', 'CUB', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'ECU', 'EGY', 'EMU', 'ERI', 'ESP', 'EST', 'ETH', 'EUU', 'FCS', 'FIN', 'FJI', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR', 'GEO', 'GHA', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HIC', 'HKG', 'HND', 'HPC', 'HRV', 'HTI', 'HUN', 'IBD', 'IBT', 'IDA', 'IDB', 'IDN', 'IDX', 'IMN', 'IND', 'INX', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'KWT', 'LAC', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LCN', 'LDC', 'LIC', 'LIE', 'LKA', 'LMC', 'LMY', 'LSO', 'LTE', 'LTU', 'LUX', 'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEA', 'MEX', 'MHL', 'MIC', 'MKD', 'MLI', 'MLT', 'MMR', 'MNA', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAC', 'NAM', 'NCL', 'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL', 'OED', 'OMN', 'OSS', 'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRE', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'PSS', 'PST', 'PYF', 'QAT', 'ROU', 'RUS', 'RWA', 'SAS', 'SAU', 'SDN', 'SEN', 'SGP', 'SLB', 'SLE', 'SLV', 'SMR', 'SOM', 'SRB', 'SSA', 'SSD', 'SSF', 'SST', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TEA', 'TEC', 'TGO', 'THA', 'TJK', 'TKM', 'TLA', 'TLS', 'TMN', 'TON', 'TSA', 'TSS', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA', 'UKR', 'UMC', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VGB', 'VIR', 'VNM', 'VUT', 'WLD', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE']

Unik negara (population):
['Afghanistan', 'Africa Eastern and Southern', 'Africa Western and Central', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD countries)', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend', 'Latin America & Caribbean', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia', 'Least developed countries: UN classification', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low & middle income', 'Low income', 'Lower middle income', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Middle East, North Africa, Afghanistan & Pakistan', 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)', 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)', 'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Not classified', 'OECD members', 'Oman', 'Other small states', 'Pacific island small states', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Post-demographic dividend', 'Pre-demographic dividend', 'Puerto Rico (US)', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia', 'Small states', 'Solomon Islands', 'Somalia, Fed. Rep.', 'South Africa', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Martin (French part)', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

# TRANSFORM

Setelah pengecekan, ditemukan:
- Nilai kosong di Mortality (22), Life Expectancy (1), Population (1), Income Level (20-29)
- Inkonsistensi bahasa antara nama negara Inggris vs Indonesia
- Jenis kelamin tidak baku (tidak_diketahui) dan level pendapatan Not classified

Semua telah dibersihkan: drop missing, mapping negara via googletrans + fuzzy, dan kategorisasi ulang.
Hasil: 0 missing value, 0 duplikat di semua tabel.

## Pembersihan data

In [21]:

print("Mortality:")
n0 = len(df_mortality)
df_mortality = df_mortality.dropna(subset=['2017', '2018', '2019', '2020'], how='all').reset_index(drop=True)
print(f"  Drop missing: {n0} -> {len(df_mortality)} baris ({n0 - len(df_mortality)} dihapus)")

print("\nLife expectancy:")
n0 = len(df_life_expectancy)
df_life_expectancy = df_life_expectancy.dropna(subset=['2017', '2018', '2019', '2020'], how='all').reset_index(drop=True)
print(f"  Drop missing: {n0} -> {len(df_life_expectancy)} baris ({n0 - len(df_life_expectancy)} dihapus)")

print("\nPopulation:")
n0 = len(df_population)
df_population = df_population.dropna(subset=['2017', '2018', '2019', '2020'], how='all').reset_index(drop=True)
print(f"  Drop missing: {n0} -> {len(df_population)} baris ({n0 - len(df_population)} dihapus)")

Mortality:
  Drop missing: 266 -> 244 baris (22 dihapus)

Life expectancy:
  Drop missing: 266 -> 265 baris (1 dihapus)

Population:
  Drop missing: 266 -> 265 baris (1 dihapus)

In [22]:
print("Income level - drop NaN:")
n0 = len(df_income_level)
df_income_level = df_income_level.dropna(subset=['kode_negara']).reset_index(drop=True)
print(f"  Drop: {n0} -> {len(df_income_level)} baris ({n0 - len(df_income_level)} dihapus)")

print("\nIsi NaN gdp_per_capita:")
n_null = df_income_level['gdp_per_capita'].isna().sum()
median_gdp = df_income_level.groupby('level_pendapatan')['gdp_per_capita'].transform('median')
df_income_level['gdp_per_capita'] = df_income_level['gdp_per_capita'].fillna(median_gdp)
# sisanya yang masih NaN (karena groupnya semua NaN) diisi median global
df_income_level['gdp_per_capita'] = df_income_level['gdp_per_capita'].fillna(df_income_level['gdp_per_capita'].median())
print(f"  {n_null} baris diisi dengan median per level_pendapatan")

# 5. Income Level — Kategorikan Not classified -> Unknown
print("\nLevel pendapatan:")
print(f"  Sebelum: {df_income_level['level_pendapatan'].unique()}")
df_income_level['level_pendapatan'] = df_income_level['level_pendapatan'].replace('Not classified', 'Unknown')
n_lvl_null = df_income_level['level_pendapatan'].isna().sum()
df_income_level = df_income_level.dropna(subset=['level_pendapatan']).reset_index(drop=True)
print(f"  Sesudah: {df_income_level['level_pendapatan'].unique()}")
print(f"  {n_lvl_null} baris dengan level_pendapatan NaN dihapus")
print(f"  Total akhir: {len(df_income_level)} baris")

Income level - drop NaN:
  Drop: 1064 -> 1044 baris (20 dihapus)

Isi NaN gdp_per_capita:
  25 baris diisi dengan median per level_pendapatan

Level pendapatan:
  Sebelum: ['Aggregates' 'Low income' 'Upper middle income' 'High income'
 'Lower middle income' 'Not classified']
  Sesudah: ['Aggregates' 'Low income' 'Upper middle income' 'High income'
 'Lower middle income' 'Unknown']
  0 baris dengan level_pendapatan NaN dihapus
  Total akhir: 1044 baris

In [23]:
# 6. Mapping negara Cause of Death (Indonesia -> Inggris -> kode_negara)
from difflib import SequenceMatcher as SM
from googletrans import Translator

print("MAPPING NEGARA CAUSE OF DEATH :")

id_names = sorted(df_cause_of_death['negara'].unique())
en_names = dict(zip(df_mortality['negara'].str.lower(), df_mortality['negara']))
en_names.update(dict(zip(df_life_expectancy['negara'].str.lower(), df_life_expectancy['negara'])))
en_code = dict(zip(df_mortality['negara'], df_mortality['kode_negara']))
en_code.update(dict(zip(df_life_expectancy['negara'], df_life_expectancy['kode_negara'])))

print(f"  Negara unik di Cause of Death: {len(id_names)}")
print(f"  Referensi nama Inggris: {len(en_names)}")

# Override terjemahan tidak akurat
manual_override = {
    'Belanda': 'Netherlands',
    'Prancis': 'France',
    'Spanyol': 'Spain',
    'Rusia': 'Russian Federation',
    'Korea selatan': 'Korea, Rep.',
    'Kirgizstan': 'Kyrgyz Republic',
    'Mesir': 'Egypt, Arab Rep.',
    'Serbia dan montenegro': 'Serbia',
    'Hong kong (cina)': 'Hong Kong SAR, China',
    'Antilen belanda': 'Curacao',
    'Guyana prancis': 'France',
    'Guadeloupe': 'France',
    'Martinique': 'France',
    'Reunion': 'France',
    'Montserrat': 'United Kingdom',
    'Wallis dan futuna': 'France',
}

translator = Translator()
mapping = {}
unmapped = []

for id_name in id_names:
    if id_name in manual_override:
        target = manual_override[id_name]
        if target in en_code:
            mapping[id_name] = (target, en_code[target])
            continue
    
    try:
        translated = translator.translate(id_name, src='id', dest='en').text
    except:
        translated = id_name
    
    en_key = translated.strip().lower()
    
    if en_key in en_names:
        real_en = en_names[en_key]
        mapping[id_name] = (real_en, en_code[real_en])
    else:
        best_ratio = 0
        best_match = None
        for candidate_key, candidate_val in en_names.items():
            ratio = SM(None, en_key, candidate_key).ratio()
            if ratio > best_ratio:
                best_ratio = ratio
                best_match = candidate_val
        
        if best_ratio >= 0.6:
            mapping[id_name] = (best_match, en_code[best_match])
        else:
            unmapped.append((id_name, translated, best_match if best_match else '-', round(best_ratio, 2)))

print(f"  Berhasil di-mapping otomatis: {len(mapping)}/{len(id_names)} negara")

if unmapped:
    print(f"\n  Tidak ter-mapping ({len(unmapped)} negara):")
    for id_name, trans, best, score in unmapped:
        print(f"  {id_name} -> {best} (skor: {score})")

df_cause_of_death['negara_inggris'] = df_cause_of_death['negara'].map(lambda x: mapping[x][0] if x in mapping else x)
df_cause_of_death['kode_negara'] = df_cause_of_death['negara'].map(lambda x: mapping[x][1] if x in mapping else None)

n_unmapped_final = df_cause_of_death['kode_negara'].isna().sum()
print(f"\n  Final: {n_unmapped_final} baris tanpa kode_negara (akan di-drop)")
df_cause_of_death = df_cause_of_death.dropna(subset=['kode_negara']).reset_index(drop=True)
df_cause_of_death['kode_negara'] = df_cause_of_death['kode_negara'].astype(str)
print(f"  Setelah drop: {len(df_cause_of_death)} baris")

MAPPING NEGARA CAUSE OF DEATH :
  Negara unik di Cause of Death: 125
  Referensi nama Inggris: 265

C:\Users\LUCKY SURYA\AppData\Local\Temp\ipykernel_16416\2349478647.py:50: RuntimeWarning: coroutine 'Translator.translate' was never awaited
  translated = id_name
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

  Berhasil di-mapping otomatis: 117/125 negara

  Tidak ter-mapping (8 negara):
  Afrika selatan -> Tajikistan (skor: 0.58)
  Ceko -> Cameroon (skor: 0.5)
  Kepulauan cayman -> Panama (skor: 0.55)
  Makedonia utara -> North Macedonia (skor: 0.53)
  Republik dominika -> Dominica (skor: 0.56)
  Selandia baru -> Saudi Arabia (skor: 0.56)
  Swiss -> Eswatini (skor: 0.46)
  Yunani -> Tanzania (skor: 0.57)

  Final: 55858 baris tanpa kode_negara (akan di-drop)
  Setelah drop: 843682 baris

In [24]:
print('Jenis kelamin:')
print(f"  Sebelum: {df_cause_of_death['jenis_kelamin'].unique()}")
df_cause_of_death['jenis_kelamin'] = df_cause_of_death['jenis_kelamin'].replace('tidak_diketahui', 'Unknown')
print(f"  Sesudah: {df_cause_of_death['jenis_kelamin'].unique()}")

Jenis kelamin:
  Sebelum: ['pria' 'wanita' 'tidak_diketahui']
  Sesudah: ['pria' 'wanita' 'Unknown']

In [25]:
# import os
# OUT = r'C:\Users\LUCKY SURYA\Documents\kuliah\semester 4\data warehouse\UAS\dataset 4\clean'
# os.makedirs(OUT, exist_ok=True)

# df_mortality.to_csv(os.path.join(OUT, 'mortality_clean.csv'), index=False)
# df_life_expectancy.to_csv(os.path.join(OUT, 'life_expectancy_clean.csv'), index=False)
# df_cause_of_death.to_csv(os.path.join(OUT, 'penyebab_kematian_clean.csv'), index=False)
# df_income_level.to_csv(os.path.join(OUT, 'income_level_clean.csv'), index=False)
# df_population.to_csv(os.path.join(OUT, 'population_clean.csv'), index=False)

# print("=== SEMUA DATASET TERSIMPAN ===")
# print(f"  Mortality        : {len(df_mortality)} baris -> {os.path.join(OUT, 'mortality_clean.csv')}")
# print(f"  Life Expectancy  : {len(df_life_expectancy)} baris -> {os.path.join(OUT, 'life_expectancy_clean.csv')}")
# print(f"  Cause of Death   : {len(df_cause_of_death)} baris -> {os.path.join(OUT, 'penyebab_kematian_clean.csv')}")
# print(f"  Income Level     : {len(df_income_level)} baris -> {os.path.join(OUT, 'income_level_clean.csv')}")
# print(f"  Population       : {len(df_population)} baris -> {os.path.join(OUT, 'population_clean.csv')}")

Star schema terdiri dari 6 dimensi (DimCountry, DimYear, DimIncomeLevel, DimCause, DimSex, DimAgeGroup)
dan 2 fakta (FactCountryYear, FactDeath).

## Star schema

In [26]:
YEARS = ['2017', '2018', '2019', '2020']

def unpivot(df, value_name):
    melted = df.melt(
        id_vars=['kode_negara', 'negara'],
        value_vars=YEARS,
        var_name='tahun',
        value_name=value_name
    )
    melted['tahun'] = melted['tahun'].astype(int)
    return melted

print('Unpivot wide ke long:')

long_mortality = unpivot(df_mortality, 'mortality_rate')
print(f'  Mortality unpivot: {len(long_mortality)} baris')

long_life = unpivot(df_life_expectancy, 'life_expectancy')
print(f'  Life Expectancy unpivot: {len(long_life)} baris')

long_pop = unpivot(df_population, 'population')
print(f'  Population unpivot: {len(long_pop)} baris')

Unpivot wide ke long:
  Mortality unpivot: 976 baris
  Life Expectancy unpivot: 1060 baris
  Population unpivot: 1060 baris

In [27]:

# DimCountry — union semua negara
df_all_country = pd.concat([
    long_mortality[['kode_negara', 'negara']],
    long_life[['kode_negara', 'negara']],
    long_pop[['kode_negara', 'negara']],
    df_income_level[['kode_negara', 'negara']],
]).drop_duplicates('kode_negara').reset_index(drop=True)
df_dim_country = df_all_country.copy()
n = len(df_dim_country)
df_dim_country['country_id'] = [f'C{str(i).zfill(3)}' for i in range(1, n + 1)]
df_dim_country = df_dim_country[['country_id', 'kode_negara', 'negara']]
print(f'DimCountry: {len(df_dim_country)} baris (C001-C{n})')

# DimYear
all_years = sorted(set(
    long_mortality['tahun'].unique().tolist() +
    long_life['tahun'].unique().tolist() +
    long_pop['tahun'].unique().tolist() +
    df_income_level['tahun'].unique().tolist() +
    df_cause_of_death['tahun'].unique().tolist()
))
df_dim_year = pd.DataFrame({
    'year_id': [f'YR{str(i).zfill(3)}' for i in range(1, len(all_years) + 1)],
    'tahun': all_years
})
print(f'DimYear: {len(df_dim_year)} baris ({list(df_dim_year["year_id"])})')

# DimIncomeLevel
df_dim_income = (
    df_income_level[['level_pendapatan']]
    .drop_duplicates('level_pendapatan')
    .reset_index(drop=True)
)
n = len(df_dim_income)
df_dim_income['income_level_id'] = [f'IL{str(i).zfill(3)}' for i in range(1, n + 1)]
df_dim_income = df_dim_income[['income_level_id', 'level_pendapatan']]
print(f'DimIncomeLevel: {len(df_dim_income)} baris (IL001-IL{n})')

DimCountry: 265 baris (C001-C265)
DimYear: 4 baris (['YR001', 'YR002', 'YR003', 'YR004'])
DimIncomeLevel: 6 baris (IL001-IL6)

In [28]:
# DimCause
df_dim_cause = (
    df_cause_of_death[['penyebab_kematian']]
    .drop_duplicates('penyebab_kematian')
    .reset_index(drop=True)
)
n = len(df_dim_cause)
df_dim_cause['cause_id'] = [f'CS{str(i).zfill(5)}' for i in range(1, n + 1)]
df_dim_cause = df_dim_cause[['cause_id', 'penyebab_kematian']]
print(f'DimCause: {len(df_dim_cause)} baris (CS00001-CS{n})')

# DimSex
df_dim_sex = (
    df_cause_of_death[['jenis_kelamin']]
    .drop_duplicates('jenis_kelamin')
    .reset_index(drop=True)
)
n = len(df_dim_sex)
df_dim_sex['sex_id'] = [f'SX{str(i).zfill(3)}' for i in range(1, n + 1)]
df_dim_sex = df_dim_sex[['sex_id', 'jenis_kelamin']]
print(f'DimSex: {len(df_dim_sex)} baris (SX001-SX{n})')

# DimAgeGroup
df_dim_age = (
    df_cause_of_death[['kelompok_umur']]
    .drop_duplicates('kelompok_umur')
    .reset_index(drop=True)
)
n = len(df_dim_age)
df_dim_age['age_group_id'] = [f'AG{str(i).zfill(3)}' for i in range(1, n + 1)]
df_dim_age = df_dim_age[['age_group_id', 'kelompok_umur']]
print(f'DimAgeGroup: {len(df_dim_age)} baris (AG001-AG{n})')

DimCause: 8470 baris (CS00001-CS8470)
DimSex: 3 baris (SX001-SX3)
DimAgeGroup: 7 baris (AG001-AG7)

In [29]:
# 3. FACT TABLES

# FactCountryYear: gabung unpivot + income level
print('FactCountryYear:')

fact_cy = long_mortality.merge(
    long_life[['kode_negara', 'tahun', 'life_expectancy']],
    on=['kode_negara', 'tahun'], how='inner'
).merge(
    long_pop[['kode_negara', 'tahun', 'population']],
    on=['kode_negara', 'tahun'], how='inner'
).merge(
    df_income_level[['kode_negara', 'tahun', 'gdp_per_capita', 'level_pendapatan']],
    on=['kode_negara', 'tahun'], how='left'
)

# Map FK
country_map = dict(zip(df_dim_country['kode_negara'], df_dim_country['country_id']))
year_map = dict(zip(df_dim_year['tahun'], df_dim_year['year_id']))
income_map = dict(zip(df_dim_income['level_pendapatan'], df_dim_income['income_level_id']))

fact_cy['country_id'] = fact_cy['kode_negara'].map(country_map)
fact_cy['year_id'] = fact_cy['tahun'].map(year_map)
fact_cy['income_level_id'] = fact_cy['level_pendapatan'].map(income_map)
before = len(fact_cy)
fact_cy = fact_cy.dropna(subset=['income_level_id']).reset_index(drop=True)
n = len(fact_cy)
fact_cy.insert(0, 'fact_country_year_id', [f'FCY{str(i).zfill(5)}' for i in range(1, n + 1)])
fact_cy = fact_cy[['fact_country_year_id', 'country_id', 'year_id', 'income_level_id',
                    'mortality_rate', 'life_expectancy', 'population', 'gdp_per_capita']]
print(f'  Drop aggregate tanpa income_level: {before} -> {n} baris')
print(f'  {n} baris (FCY00001-FCY{n})')
print(f'  Columns: {list(fact_cy.columns)}')

FactCountryYear:
  Drop aggregate tanpa income_level: 976 -> 960 baris
  960 baris (FCY00001-FCY960)
  Columns: ['fact_country_year_id', 'country_id', 'year_id', 'income_level_id', 'mortality_rate', 'life_expectancy', 'population', 'gdp_per_capita']

In [30]:
# FactDeath
print('FactDeath:')

cause_map = dict(zip(df_dim_cause['penyebab_kematian'], df_dim_cause['cause_id']))
sex_map = dict(zip(df_dim_sex['jenis_kelamin'], df_dim_sex['sex_id']))
age_map = dict(zip(df_dim_age['kelompok_umur'], df_dim_age['age_group_id']))

fact_death = df_cause_of_death.copy()
fact_death['country_id'] = fact_death['kode_negara'].map(country_map)
fact_death['year_id'] = fact_death['tahun'].map(year_map)
fact_death['cause_id'] = fact_death['penyebab_kematian'].map(cause_map)
fact_death['sex_id'] = fact_death['jenis_kelamin'].map(sex_map)
fact_death['age_group_id'] = fact_death['kelompok_umur'].map(age_map)

n = len(fact_death)
fact_death.insert(0, 'fact_death_id', [f'FD{str(i).zfill(7)}' for i in range(1, n + 1)])
fact_death = fact_death[['fact_death_id', 'country_id', 'year_id', 'tahun', 'cause_id', 'sex_id',
                        'age_group_id', 'jumlah_kematian']]
print(f'  {len(fact_death)} baris (FD0000001-FD{n})')
print(f'  Columns: {list(fact_death.columns)}')

FactDeath:
  843682 baris (FD0000001-FD843682)
  Columns: ['fact_death_id', 'country_id', 'year_id', 'tahun', 'cause_id', 'sex_id', 'age_group_id', 'jumlah_kematian']

In [31]:
fact_death.head(10)

,fact_death_id,country_id,year_id,tahun,cause_id,sex_id,age_group_id,jumlah_kematian
0,FD0000001,C206,YR001,2017,CS00001,SX001,AG001,429
1,FD0000002,C206,YR001,2017,CS00001,SX002,AG001,325
2,FD0000003,C206,YR001,2017,CS00002,SX001,AG001,22
3,FD0000004,C206,YR001,2017,CS00002,SX002,AG001,25
4,FD0000005,C206,YR001,2017,CS00003,SX001,AG001,0
5,FD0000006,C206,YR001,2017,CS00003,SX002,AG001,0
6,FD0000007,C206,YR001,2017,CS00004,SX001,AG001,1
7,FD0000008,C206,YR001,2017,CS00004,SX002,AG001,1
8,FD0000009,C206,YR001,2017,CS00005,SX001,AG001,0
9,FD0000010,C206,YR001,2017,CS00005,SX002,AG001,0

In [32]:
import os

# OUT = r'C:\Users\LUCKY SURYA\Documents\kuliah\semester 4\data warehouse\UAS\dataset 4\clean'
# STAR_OUT = os.path.join(OUT, 'star-schema')
# os.makedirs(STAR_OUT, exist_ok=True)

# df_dim_country.to_csv(os.path.join(STAR_OUT, 'DimCountry.csv'), index=False)
# df_dim_year.to_csv(os.path.join(STAR_OUT, 'DimYear.csv'), index=False)
# df_dim_income.to_csv(os.path.join(STAR_OUT, 'DimIncomeLevel.csv'), index=False)
# df_dim_cause.to_csv(os.path.join(STAR_OUT, 'DimCause.csv'), index=False)
# df_dim_sex.to_csv(os.path.join(STAR_OUT, 'DimSex.csv'), index=False)
# df_dim_age.to_csv(os.path.join(STAR_OUT, 'DimAgeGroup.csv'), index=False)
# fact_cy.to_csv(os.path.join(STAR_OUT, 'FactCountryYear.csv'), index=False)
# fact_death.to_csv(os.path.join(STAR_OUT, 'FactDeath.csv'), index=False)

print('Star schema tersimpan:')
print(f'  DimCountry:     {len(df_dim_country)} baris')
print(f'  DimYear:        {len(df_dim_year)} baris')
print(f'  DimIncomeLevel: {len(df_dim_income)} baris')
print(f'  DimCause:       {len(df_dim_cause)} baris')
print(f'  DimSex:         {len(df_dim_sex)} baris')
print(f'  DimAgeGroup:    {len(df_dim_age)} baris')
print(f'  FactCountryYear:{len(fact_cy)} baris')
print(f'  FactDeath:      {len(fact_death)} baris')
# print(f'  Lokasi: {STAR_OUT}')

Star schema tersimpan:
  DimCountry:     265 baris
  DimYear:        4 baris
  DimIncomeLevel: 6 baris
  DimCause:       8470 baris
  DimSex:         3 baris
  DimAgeGroup:    7 baris
  FactCountryYear:960 baris
  FactDeath:      843682 baris

# Load ke database

In [33]:
DB_CONFIG = {
    'host': 'aws-1-ap-southeast-1.pooler.supabase.com',
    'port': 5432,
    'dbname': 'postgres',
    'user': 'postgres.gxkjwqjpcstntdbubnrm',
    'password': 'luckysuryar123'
}

DB_URL = f"postgresql://{DB_CONFIG['user']}:{DB_CONFIG['password']}@{DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['dbname']}"
print('DB URL (tersembunyi):', DB_URL.replace(DB_CONFIG['password'], '***'))

DB URL (tersembunyi): postgresql://postgres.gxkjwqjpcstntdbubnrm:***@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres

## DDL

In [34]:
DDL_SQL = '''

CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

CREATE TABLE DimCountry (
    country_id VARCHAR(6) PRIMARY KEY,
    kode_negara VARCHAR(10),
    negara VARCHAR(100)
);

CREATE TABLE DimYear (
    year_id VARCHAR(6) PRIMARY KEY,
    tahun INTEGER UNIQUE
);

CREATE TABLE DimIncomeLevel (
    income_level_id VARCHAR(6) PRIMARY KEY,
    level_pendapatan VARCHAR(50)
);

CREATE TABLE DimCause (
    cause_id VARCHAR(7) PRIMARY KEY,
    penyebab_kematian VARCHAR(255)
);

CREATE TABLE DimSex (
    sex_id VARCHAR(6) PRIMARY KEY,
    jenis_kelamin VARCHAR(20)
);

CREATE TABLE DimAgeGroup (
    age_group_id VARCHAR(6) PRIMARY KEY,
    kelompok_umur VARCHAR(100)
);

CREATE TABLE FactCountryYear (
    fact_country_year_id VARCHAR(8) PRIMARY KEY,
    country_id VARCHAR(6) REFERENCES DimCountry(country_id),
    year_id VARCHAR(6) REFERENCES DimYear(year_id),
    income_level_id VARCHAR(6) REFERENCES DimIncomeLevel(income_level_id),
    mortality_rate NUMERIC,
    life_expectancy NUMERIC,
    population NUMERIC,
    gdp_per_capita NUMERIC
);

CREATE TABLE FactDeath (
    fact_death_id VARCHAR(10),
    country_id VARCHAR(6) REFERENCES DimCountry(country_id),
    year_id VARCHAR(6) REFERENCES DimYear(year_id),
    tahun INTEGER NOT NULL,
    cause_id VARCHAR(7) REFERENCES DimCause(cause_id),
    sex_id VARCHAR(6) REFERENCES DimSex(sex_id),
    age_group_id VARCHAR(6) REFERENCES DimAgeGroup(age_group_id),
    jumlah_kematian INTEGER,

    PRIMARY KEY (fact_death_id, tahun)
) PARTITION BY RANGE (tahun);

CREATE TABLE FactDeath_2017
PARTITION OF FactDeath
FOR VALUES FROM (2017) TO (2018);

CREATE TABLE FactDeath_2018
PARTITION OF FactDeath
FOR VALUES FROM (2018) TO (2019);

CREATE TABLE FactDeath_2019
PARTITION OF FactDeath
FOR VALUES FROM (2019) TO (2020);

CREATE TABLE FactDeath_2020
PARTITION OF FactDeath
FOR VALUES FROM (2020) TO (2021);

CREATE INDEX idx_fd_country
ON FactDeath(country_id);

CREATE INDEX idx_fd_tahun
ON FactDeath(tahun);

CREATE INDEX idx_fd_cause
ON FactDeath(cause_id);

CREATE INDEX idx_fd_sex
ON FactDeath(sex_id);

CREATE INDEX idx_fd_agegroup
ON FactDeath(age_group_id);

CREATE INDEX idx_fd_country_year
ON FactDeath(country_id, tahun);

CREATE INDEX idx_fd_cause_year
ON FactDeath(cause_id, tahun);

CREATE INDEX idx_fcy_country
ON FactCountryYear(country_id);

CREATE INDEX idx_fcy_year
ON FactCountryYear(year_id);

CREATE INDEX idx_fcy_country_year
ON FactCountryYear(country_id, year_id);

CREATE MATERIALIZED VIEW mv_deaths_by_country_year AS
SELECT
    fd.country_id,
    c.negara,
    fd.tahun,
    SUM(fd.jumlah_kematian) AS total_deaths
FROM FactDeath fd
JOIN DimCountry c
    ON c.country_id = fd.country_id
GROUP BY
    fd.country_id,
    c.negara,
    fd.tahun;

CREATE INDEX idx_mv_country_year
ON mv_deaths_by_country_year(country_id, tahun);

CREATE MATERIALIZED VIEW mv_deaths_by_cause AS
SELECT
    dc.penyebab_kematian,
    fd.tahun,
    SUM(fd.jumlah_kematian) AS total_deaths
FROM FactDeath fd
JOIN DimCause dc
    ON dc.cause_id = fd.cause_id
GROUP BY
    dc.penyebab_kematian,
    fd.tahun;

CREATE INDEX idx_mv_cause_year
ON mv_deaths_by_cause(penyebab_kematian, tahun);

CREATE MATERIALIZED VIEW mv_deaths_by_age AS
SELECT
    da.kelompok_umur,
    fd.tahun,
    SUM(fd.jumlah_kematian) AS total_deaths
FROM FactDeath fd
JOIN DimAgeGroup da
    ON da.age_group_id = fd.age_group_id
GROUP BY
    da.kelompok_umur,
    fd.tahun;

CREATE INDEX idx_mv_age
ON mv_deaths_by_age(kelompok_umur);

CREATE INDEX idx_mv_age_year
ON mv_deaths_by_age(kelompok_umur, tahun);
'''

In [35]:
REFRESH_DDL = '''
REFRESH MATERIALIZED VIEW mv_deaths_by_country_year;
REFRESH MATERIALIZED VIEW mv_deaths_by_cause;
REFRESH MATERIALIZED VIEW mv_deaths_by_age;
'''

In [36]:
RESET_SQL = """
DROP MATERIALIZED VIEW IF EXISTS mv_deaths_by_country_year;
DROP MATERIALIZED VIEW IF EXISTS mv_deaths_by_cause;
DROP MATERIALIZED VIEW IF EXISTS mv_deaths_by_age;

DROP TABLE IF EXISTS factdeath CASCADE;
DROP TABLE IF EXISTS factdeath_2017 CASCADE;
DROP TABLE IF EXISTS factdeath_2018 CASCADE;
DROP TABLE IF EXISTS factdeath_2019 CASCADE;
DROP TABLE IF EXISTS factdeath_2020 CASCADE;
DROP TABLE IF EXISTS factcountryyear CASCADE;

DROP TABLE IF EXISTS dimcountry CASCADE;
DROP TABLE IF EXISTS dimyear CASCADE;
DROP TABLE IF EXISTS dimincomelevel CASCADE;
DROP TABLE IF EXISTS dimcause CASCADE;
DROP TABLE IF EXISTS dimsex CASCADE;
DROP TABLE IF EXISTS dimagegroup CASCADE;
"""

In [37]:
! pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\lucky surya\atoti-env\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\lucky surya\atoti-env\lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in c:\users\lucky surya\atoti-env\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lucky surya\atoti-env\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
import psycopg2
from psycopg2.extras import execute_values

def insert_df(cur, table, df, cols):
    """Bulk insert DataFrame rows into a PostgreSQL table."""
    rows = [tuple(row) for row in df[cols].values]
    sql = f"INSERT INTO {table} ({', '.join(cols)}) VALUES %s"
    execute_values(cur, sql, rows, template=None, page_size=1000)
    print(f"  {table}: {len(rows)} baris ditambahkan")

conn = psycopg2.connect(
    host=DB_CONFIG['host'],
    port=DB_CONFIG['port'],
    dbname=DB_CONFIG['dbname'],
    user=DB_CONFIG['user'],
    password=DB_CONFIG['password']
)
conn.autocommit = True
cur = conn.cursor()

print('Drop tables:')
cur.execute(RESET_SQL)
print('selesai')

print('\nCreate tables:')
cur.execute(DDL_SQL)
print('selesai')

print('\nInsert dimension:')
insert_df(cur, 'DimCountry', df_dim_country, ['country_id', 'kode_negara', 'negara'])
insert_df(cur, 'DimYear', df_dim_year, ['year_id', 'tahun'])
insert_df(cur, 'DimIncomeLevel', df_dim_income, ['income_level_id', 'level_pendapatan'])
insert_df(cur, 'DimCause', df_dim_cause, ['cause_id', 'penyebab_kematian'])
insert_df(cur, 'DimSex', df_dim_sex, ['sex_id', 'jenis_kelamin'])
insert_df(cur, 'DimAgeGroup', df_dim_age, ['age_group_id', 'kelompok_umur'])

print('\nInsert fact:')
n0 = len(fact_cy)
fact_cy_clean = fact_cy.dropna(subset=['country_id', 'year_id', 'income_level_id']).reset_index(drop=True)
dropped = n0 - len(fact_cy_clean)
if dropped:
    print(f'  {dropped} baris FactCountryYear di-drop')
insert_df(cur, 'FactCountryYear', fact_cy_clean,
            ['fact_country_year_id', 'country_id', 'year_id', 'income_level_id',
            'mortality_rate', 'life_expectancy', 'population', 'gdp_per_capita'])

n0 = len(fact_death)
fact_death_clean = fact_death.dropna(subset=['country_id', 'year_id', 'cause_id', 'sex_id', 'age_group_id']).reset_index(drop=True)
dropped = n0 - len(fact_death_clean)
if dropped:
    print(f'  {dropped} baris FactDeath di-drop')
insert_df(cur, 'FactDeath', fact_death_clean,
            ['fact_death_id', 'country_id', 'year_id', 'tahun', 'cause_id',
            'sex_id', 'age_group_id', 'jumlah_kematian'])

print('\nRefresh MV:')
cur.execute(REFRESH_DDL)
print('selesai.')

cur.close()
conn.close()
print('\nload selesai')

Drop tables:
selesai

Create tables:
selesai

Insert dimension:
  DimCountry: 265 baris ditambahkan
  DimYear: 4 baris ditambahkan
  DimIncomeLevel: 6 baris ditambahkan
  DimCause: 8470 baris ditambahkan
  DimSex: 3 baris ditambahkan
  DimAgeGroup: 7 baris ditambahkan

Insert fact:
  FactCountryYear: 960 baris ditambahkan
  FactDeath: 843682 baris ditambahkan

Refresh MV:
selesai.

load selesai

# OLAP

In [39]:
import atoti as tt

session = tt.Session.start()

Welcome to Atoti 0.9.13!

By using this community edition, you agree with the license available at https://docs.activeviam.com/products/atoti/python-sdk/latest/eula.html.
Browse the official documentation at https://docs.activeviam.com/products/atoti/python-sdk.
Join the community at https://www.atoti.io/register.

Atoti collects telemetry data, which is used to help understand how to improve the product.
If you don't wish to send usage data, you can request a trial license at https://www.atoti.io/evaluation-license-request.

You can hide this message by setting the `ATOTI_HIDE_EULA_MESSAGE` environment variable to True.

In [40]:
df_dim_country = df_dim_country.astype({
    "country_id": "string",
    "kode_negara": "string",
    "negara": "string"
})

df_dim_year = df_dim_year.astype({
    "year_id": "string",
    "tahun": "string"
})

df_dim_income = df_dim_income.astype({
    "income_level_id": "string",
    "level_pendapatan": "string"
})

df_dim_cause = df_dim_cause.astype({
    "cause_id": "string",
    "penyebab_kematian": "string"
})

df_dim_sex = df_dim_sex.astype({
    "sex_id": "string",
    "jenis_kelamin": "string"
})

df_dim_age = df_dim_age.astype({
    "age_group_id": "string",
    "kelompok_umur": "string"
})

fact_cy_clean = fact_cy_clean.astype({
    "fact_country_year_id": "string",
    "country_id": "string",
    "year_id": "string",
    "income_level_id": "string",
    "mortality_rate": "float64",
    "life_expectancy": "float64",
    "population": "float64",
    "gdp_per_capita": "float64"
})

fact_death_clean = fact_death_clean.astype({
    "fact_death_id": "string",
    "country_id": "string",
    "year_id": "string",
    "cause_id": "string",
    "sex_id": "string",
    "age_group_id": "string",
    "jumlah_kematian": "int64"
})

fact_death_clean.drop(columns=["tahun"], inplace=True)

In [41]:
country_tbl = session.read_pandas(df_dim_country, table_name='country', keys=["country_id"])
year_tbl = session.read_pandas(df_dim_year, table_name='year', keys=["year_id"])
income_tbl = session.read_pandas(df_dim_income, table_name='income', keys=["income_level_id"])
cause_tbl = session.read_pandas(df_dim_cause, table_name='cause', keys=["cause_id"])
sex_tbl = session.read_pandas(df_dim_sex, table_name='sex', keys=["sex_id"])
age_tbl = session.read_pandas(df_dim_age, table_name='age', keys=["age_group_id"])

fact_country_year_tbl = session.read_pandas(fact_cy_clean, table_name='country_year', keys=["country_id", "year_id"])
fact_death_tbl = session.read_pandas(fact_death_clean, table_name='death', keys=["country_id", "year_id", "cause_id", "sex_id", "age_group_id"])

print('selesai')

selesai

In [42]:
fact_country_year_tbl.join(
    country_tbl,
    fact_country_year_tbl["country_id"] == country_tbl["country_id"]
)

fact_country_year_tbl.join(
    year_tbl,
    fact_country_year_tbl["year_id"] == year_tbl["year_id"]
)

fact_country_year_tbl.join(
    income_tbl,
    fact_country_year_tbl["income_level_id"] == income_tbl["income_level_id"]
)

In [43]:
fact_death_tbl.join(
    country_tbl,
    fact_death_tbl["country_id"] == country_tbl["country_id"]
)

fact_death_tbl.join(
    year_tbl,
    fact_death_tbl["year_id"] == year_tbl["year_id"]
)

fact_death_tbl.join(
    cause_tbl,
    fact_death_tbl["cause_id"] == cause_tbl["cause_id"]
)
fact_death_tbl.join(
    sex_tbl,
    fact_death_tbl["sex_id"] == sex_tbl["sex_id"]
)

fact_death_tbl.join(
    age_tbl,
    fact_death_tbl["age_group_id"] == age_tbl["age_group_id"]
)

In [44]:
session.tables.schema

erDiagram
  "country" {
    non-null String PK "country_id"
    non-null String "kode_negara"
    non-null String "negara"
  }
  "year" {
    non-null String PK "year_id"
    non-null String "tahun"
  }
  "income" {
    non-null String PK "income_level_id"
    non-null String "level_pendapatan"
  }
  "cause" {
    non-null String PK "cause_id"
    non-null String "penyebab_kematian"
  }
  "sex" {
    non-null String PK "sex_id"
    non-null String "jenis_kelamin"
  }
  "age" {
    non-null String PK "age_group_id"
    non-null String "kelompok_umur"
  }
  "country_year" {
    non-null String "fact_country_year_id"
    non-null String PK "country_id"
    non-null String PK "year_id"
    non-null String "income_level_id"
    nullable double "mortality_rate"
    nullable double "life_expectancy"
    nullable double "population"
    nullable double "gdp_per_capita"
  }
  "death" {
    non-null String "fact_death_id"
    non-null String PK "country_id"
    non-null String PK "year_id"
    non-null String PK "cause_id"
    non-null String PK "sex_id"
    non-null String PK "age_group_id"
    nullable long "jumlah_kematian"
  }
  "country_year" }o--o| "country" : "country_id == country_id"
  "country_year" }o--o| "income" : "income_level_id == income_level_id"
  "country_year" }o--o| "year" : "year_id == year_id"
  "death" }o--o| "age" : "age_group_id == age_group_id"
  "death" }o--o| "cause" : "cause_id == cause_id"
  "death" }o--o| "country" : "country_id == country_id"
  "death" }o--o| "sex" : "sex_id == sex_id"
  "death" }o--o| "year" : "year_id == year_id"

In [45]:
#  DeathCube 
cube_death = session.create_cube(fact_death_tbl, "DeathCube")

m_death = cube_death.measures
m_death["Total Deaths"] = tt.agg.sum(fact_death_tbl["jumlah_kematian"])

#  CountryYearCube 
cube_country = session.create_cube(fact_country_year_tbl, "CountryYearCube")

m_country = cube_country.measures
m_country["Avg Life Expectancy"] = tt.agg.mean(fact_country_year_tbl["life_expectancy"])
m_country["Avg Mortality Rate"] = tt.agg.mean(fact_country_year_tbl["mortality_rate"])
m_country["Total Population"] = tt.agg.sum(fact_country_year_tbl["population"])
m_country["Avg GDP per Capita"] = tt.agg.mean(fact_country_year_tbl["gdp_per_capita"])

# Ringkasan
print("Cubes:")
print(f"DeathCube: {len(list(cube_death.hierarchies))} hierarchies, {len(list(m_death))} measures")
print(f"CountryYearCube: {len(list(cube_country.hierarchies))} hierarchies, {len(list(m_country))} measures")

Cubes:
DeathCube: 12 hierarchies, 5 measures
CountryYearCube: 8 hierarchies, 14 measures

Analisis dengan operasi Drill-down, Roll-up, Slice, dan Dice.

In [46]:
print("DeathCube levels:")
for l in cube_death.levels:
    print(f"  - {l}")
print("\nDeathCube measures:")
for m in list(m_death):
    print(f"  - {m}")
print("\nCountryYearCube levels:")
for l in cube_country.levels:
    print(f"  - {l}")
print("\nCountryYearCube measures:")
for m in list(m_country):
    print(f"  - {m}")

DeathCube levels:
  - ('country', 'kode_negara', 'kode_negara')
  - ('country', 'negara', 'negara')
  - ('death', 'cause_id', 'cause_id')
  - ('death', 'fact_death_id', 'fact_death_id')
  - ('death', 'country_id', 'country_id')
  - ('death', 'year_id', 'year_id')
  - ('death', 'age_group_id', 'age_group_id')
  - ('death', 'sex_id', 'sex_id')
  - ('year', 'tahun', 'tahun')
  - ('sex', 'jenis_kelamin', 'jenis_kelamin')
  - ('cause', 'penyebab_kematian', 'penyebab_kematian')
  - ('age', 'kelompok_umur', 'kelompok_umur')

DeathCube measures:
  - Total Deaths
  - contributors.COUNT
  - jumlah_kematian.MEAN
  - jumlah_kematian.SUM
  - update.TIMESTAMP

CountryYearCube levels:
  - ('income', 'level_pendapatan', 'level_pendapatan')
  - ('country', 'kode_negara', 'kode_negara')
  - ('country', 'negara', 'negara')
  - ('year', 'tahun', 'tahun')
  - ('country_year', 'country_id', 'country_id')
  - ('country_year', 'fact_country_year_id', 'fact_country_year_id')
  - ('country_year', 'year_id', 'year_id')
  - ('country_year', 'income_level_id', 'income_level_id')

CountryYearCube measures:
  - Avg GDP per Capita
  - Avg Life Expectancy
  - Avg Mortality Rate
  - Total Population
  - contributors.COUNT
  - gdp_per_capita.MEAN
  - gdp_per_capita.SUM
  - life_expectancy.MEAN
  - life_expectancy.SUM
  - mortality_rate.MEAN
  - mortality_rate.SUM
  - population.MEAN
  - population.SUM
  - update.TIMESTAMP

## Q1: Negara dengan kematian tertinggi

In [47]:
q1_country = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["negara"]]
).sort_values("Total Deaths", ascending=False).head(10)
print("Top 10 negara kematian:")
q1_country

Top 10 negara kematian:

                          Total Deaths
negara
Turks and Caicos Islands      23773640
Russian Federation            15930711
Georgia                       10913235
Brazil                        10786470
Gibraltar                      7623957
United Kingdom                 6206431
Italy                          5496957
Turkiye                        5145866
France                         5068261
Turkmenistan                   4977130

In [48]:
q1_drilldown = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["negara"], cube_death.levels["tahun"]]
).sort_values("Total Deaths", ascending=False).head(30)
print("Drill-down negara x tahun:")
q1_drilldown

Drill-down negara x tahun:

                                Total Deaths
negara                   tahun
Turks and Caicos Islands 2020        6765034
                         2019        5707499
                         2018        5676251
                         2017        5624856
Russian Federation       2018        5344112
                         2017        5333799
                         2019        5252800
Brazil                   2020        3045465
Georgia                  2019        2762152
                         2020        2745459
                         2018        2724908
                         2017        2680716
Brazil                   2019        2633686
                         2018        2560395
                         2017        2546924
United Kingdom           2020        2096278
Gibraltar                2020        1971023
                         2018        1909674
                         2019        1878908
                         2017        1864352
Turkiye                  2018        1734358
                         2019        1715326
                         2017        1696182
Italy                    2020        1506984
United Kingdom           2019        1412601
Italy                    2017        1409974
Turkmenistan             2020        1375290
United Kingdom           2018        1365440
France                   2020        1358301
United Kingdom           2017        1332112

## Q2: Penyebab kematian terbanyak

In [49]:
q2_cause = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["penyebab_kematian"]]
).sort_values("Total Deaths", ascending=False)
print("Kematian per penyebab:")
q2_cause

Kematian per penyebab:

                                                   Total Deaths
penyebab_kematian
All causes                                             74805769
Diseases of the circulatory system                      3727946
Acute myocardial infarction, unspecified                2865571
Malignant neoplasm: Bronchus or lung, unspecified       2372311
Ischaemic heart diseases                                2160763
...                                                         ...
Other specified diseases of inner ear                         1
Other forms of sporotrichosis                                 1
Other forms of tularaemia                                     1
Sporotrichosis                                                1
Spotted fever [tick-borne rickettsioses]                      1

[8470 rows x 1 columns]

In [50]:
q2_drilldown = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["penyebab_kematian"], cube_death.levels["tahun"]]
).sort_values("Total Deaths", ascending=False).head(20)
print("Drill-down penyebab x tahun:")
q2_drilldown

Drill-down penyebab x tahun:

                                                         Total Deaths
penyebab_kematian                                 tahun
All causes                                        2019       19270005
                                                  2017       19253365
                                                  2018       19160805
                                                  2020       17121594
COVID-19, virus identified                        2020        1417800
Diseases of the circulatory system                2018        1248353
                                                  2017        1248178
                                                  2019        1230974
Acute myocardial infarction, unspecified          2020         746363
                                                  2017         739874
Ischaemic heart diseases                          2017         726789
                                                  2018         723094
                                                  2019         710749
Acute myocardial infarction, unspecified          2019         691731
                                                  2018         687603
Malignant neoplasm: Bronchus or lung, unspecified 2017         611555
                                                  2018         601015
                                                  2019         595432
                                                  2020         564309
Pneumonia, unspecified                            2019         459253

## Q3: Populasi vs kematian vs harapan hidup

In [51]:
q3_deaths = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["negara"]]
).reset_index()

q3_pop_le = cube_country.query(
    m_country["Total Population"],
    m_country["Avg Life Expectancy"],
    levels=[cube_death.levels["negara"]]
).reset_index()

q3_merged = q3_deaths.merge(q3_pop_le, on="negara", how="inner")
print("Populasi vs kematian vs harapan hidup:")
q3_merged.head(15)

Populasi vs kematian vs harapan hidup:

,negara,Total Deaths,Total Population,Avg Life Expectancy
0,Albania,229991,10352299.0,78.85725
1,Andorra,3972,302779.0,83.02925
2,Angola,718,127358758.0,62.72775
3,Antigua and Barbuda,4642,364604.0,77.12275
4,Arab World,55734,1762318500.0,71.277652
5,Argentina,2765687,179109206.0,76.5095
6,Armenia,13595,11872400.0,75.108537
7,Australia,1300004,100539920.0,82.837195
8,Austria,677518,35434871.0,81.606098
9,Azerbaijan,50240,39911208.0,72.328
10,Bahrain,385440,5960167.0,79.99325
11,Belarus,240100,37697484.0,73.667567
12,Belgium,910141,45829796.0,81.444512
13,Bolivia,4221,46340640.0,66.49025
14,Bosnia and Herzegovina,317958,13460564.0,77.19025

## Q4: Pengaruh income level

In [52]:
q4_rollup = cube_country.query(
    m_country["Avg Life Expectancy"],
    m_country["Avg Mortality Rate"],
    levels=[cube_country.levels["level_pendapatan"]]
)
print("Rata-rata per income level:")
q4_rollup

Rata-rata per income level:

                    Avg Life Expectancy Avg Mortality Rate
level_pendapatan
Aggregates                        70.74              27.68
High income                       79.15               5.82
Low income                        61.41              51.25
Lower middle income               67.20              32.11
Unknown                           68.93              31.41
Upper middle income               72.93              15.32

In [53]:
q4_dice = cube_country.query(
    m_country["Avg Life Expectancy"],
    m_country["Total Population"],
    levels=[cube_country.levels["level_pendapatan"], cube_country.levels["tahun"]]
)
print("Income level x tahun:")
q4_dice

Income level x tahun:

                          Avg Life Expectancy   Total Population
level_pendapatan    tahun
Aggregates          2017                70.54  66,512,676,571.00
                    2018                70.85  67,342,229,593.00
                    2019                71.12  68,156,496,403.00
                    2020                70.43  68,937,288,410.00
High income         2017                79.14   1,343,479,693.00
                    2018                79.24   1,348,291,181.00
                    2019                79.45   1,352,862,824.00
                    2020                78.77   1,356,607,706.00
Low income          2017                60.22     514,890,519.00
                    2018                61.61     529,522,043.00
                    2019                61.58     544,980,983.00
                    2020                62.24     560,643,073.00
Lower middle income 2017                66.93   2,847,931,114.00
                    2018                67.25   2,888,561,818.00
                    2019                67.51   2,928,617,292.00
                    2020                67.09   2,968,398,856.00
Unknown             2017                68.33     140,231,804.00
                    2018                68.95     142,471,744.00
                    2019                69.25     144,675,481.00
                    2020                69.17     147,361,748.00
Upper middle income 2017                72.93   2,731,150,081.00
                    2018                73.23   2,751,574,852.00
                    2019                73.33   2,769,964,564.00
                    2020                72.25   2,784,871,872.00

## Q5: Tren kematian vs harapan hidup

In [54]:
q5_death_trend = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["tahun"]]
)
print("Tren kematian per tahun:")
q5_death_trend

Tren kematian per tahun:

      Total Deaths
tahun
2017    40,608,571
2018    40,354,548
2019    40,548,345
2020    34,069,995

In [55]:
q5_le_trend = cube_country.query(
    m_country["Avg Life Expectancy"],
    levels=[cube_country.levels["tahun"]]
)
print("Tren harapan hidup:")
q5_le_trend

Tren harapan hidup:

      Avg Life Expectancy
tahun
2017                71.56
2018                71.93
2019                72.11
2020                71.54

## Q6: Tren kematian tahun ke tahun

In [56]:
q6_yoy = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["tahun"]]
).sort_index()
print("Tren kematian tahun ke tahun:")
q6_yoy

Tren kematian tahun ke tahun:

       Total Deaths
tahun
2017       40608571
2018       40354548
2019       40548345
2020       34069995

In [57]:
for year in ["2017", "2018", "2019", "2020"]:
    yr = cube_death.query(
        m_death["Total Deaths"],
        levels=[cube_death.levels["negara"]],
        filter=(cube_death.levels["tahun"] == year)
    ).sort_values("Total Deaths", ascending=False).head(5)
    print(f"\n=== Top 5 Negara Tahun {year} ===")
    print(yr.to_string())

=== Top 5 Negara Tahun 2017 ===
                          Total Deaths
negara
Turks and Caicos Islands       5624856
Russian Federation             5333799
Georgia                        2680716
Brazil                         2546924
Gibraltar                      1864352

=== Top 5 Negara Tahun 2018 ===
                          Total Deaths
negara
Turks and Caicos Islands       5676251
Russian Federation             5344112
Georgia                        2724908
Brazil                         2560395
Gibraltar                      1909674

=== Top 5 Negara Tahun 2019 ===
                          Total Deaths
negara
Turks and Caicos Islands       5707499
Russian Federation             5252800
Georgia                        2762152
Brazil                         2633686
Gibraltar                      1878908

=== Top 5 Negara Tahun 2020 ===
                          Total Deaths
negara
Turks and Caicos Islands       6765034
Brazil                         3045465
Georgia                        2745459
United Kingdom                 2096278
Gibraltar                      1971023

## Q7: Gender dan kelompok umur

In [58]:
q7_sex = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["jenis_kelamin"]]
)
print("Kematian per jenis kelamin:")
q7_sex

Kematian per jenis kelamin:

              Total Deaths
jenis_kelamin
Unknown             33,740
pria            80,826,227
wanita          74,721,492

In [59]:
q7_age = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["kelompok_umur"]]
).sort_values("Total Deaths", ascending=False)
print("Kematian per kelompok umur:")
q7_age

Kematian per kelompok umur:

                                       Total Deaths
kelompok_umur
0-95+ tahun (Sangat Mendetail)            124895827
0-85+ tahun (Sangat Mendetail)             21796451
0-85+ tahun (Mendetail)                     8468730
0-75+ tahun (Cukup Mendetail)                292497
Semua usia (Paling Tidak Mendetail)          115943
0-65+ tahun (Sangat Kurang Mendetail)          6543
0-75+ tahun (Mendetail)                        5468

In [60]:
q7_dice = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["jenis_kelamin"], cube_death.levels["kelompok_umur"]]
)
print("Dice jenis kelamin x kelompok umur:")
q7_dice

Dice jenis kelamin x kelompok umur:

                                                    Total Deaths
jenis_kelamin kelompok_umur
Unknown       0-75+ tahun (Cukup Mendetail)                   20
              0-85+ tahun (Mendetail)                      5,328
              0-85+ tahun (Sangat Mendetail)               8,274
              0-95+ tahun (Sangat Mendetail)              20,118
pria          0-65+ tahun (Sangat Kurang Mendetail)        3,730
              0-75+ tahun (Cukup Mendetail)              161,333
              0-75+ tahun (Mendetail)                      3,986
              0-85+ tahun (Mendetail)                  4,289,196
              0-85+ tahun (Sangat Mendetail)          11,044,624
              0-95+ tahun (Sangat Mendetail)          65,261,439
              Semua usia (Paling Tidak Mendetail)         61,919
wanita        0-65+ tahun (Sangat Kurang Mendetail)        2,813
              0-75+ tahun (Cukup Mendetail)              131,144
              0-75+ tahun (Mendetail)                      1,482
              0-85+ tahun (Mendetail)                  4,174,206
              0-85+ tahun (Sangat Mendetail)          10,743,553
              0-95+ tahun (Sangat Mendetail)          59,614,270
              Semua usia (Paling Tidak Mendetail)         54,024

## Operasi OLAP (DRILL DOWN, DICE, SLICE)

In [61]:
print("Drill-down tahun ke penyebab:")
dd1 = cube_death.query(m_death["Total Deaths"], levels=[cube_death.levels["tahun"]])
dd1

Drill-down tahun ke penyebab:

      Total Deaths
tahun
2017    40,608,571
2018    40,354,548
2019    40,548,345
2020    34,069,995

In [62]:
print("\nDrill-down ke penyebab_kematian:")
dd2 = cube_death.query(m_death["Total Deaths"], levels=[cube_death.levels["penyebab_kematian"]])
dd2

Drill-down ke penyebab_kematian:

                                             Total Deaths
penyebab_kematian
4-Aminophenol derivatives                              25
46,XX true hermaphrodite                                7
ABO isoimmunization of fetus and newborn               98
Abdominal actinomycosis                                43
Abdominal and pelvic pain                             723
...                                                   ...
Zoster with other complications                       219
Zoster with other nervous system involvement          253
Zoster without complication                         2,690
Zygomycosis                                            11
Zygomycosis, unspecified                               10

[8470 rows x 1 columns]

In [63]:
print("Roll-up negara ke income:")
ru1 = cube_country.query(m_country["Avg Life Expectancy"], levels=[cube_country.levels["negara"]])
ru1

Roll-up negara ke income:

                            Avg Life Expectancy
negara
Afghanistan                               62.31
Africa Eastern and Southern               63.39
Africa Western and Central                57.04
Albania                                   78.86
Algeria                                   74.98
...                                         ...
West Bank and Gaza                        75.35
World                                     72.51
Yemen, Rep.                               66.51
Zambia                                    62.49
Zimbabwe                                  60.94

[240 rows x 1 columns]

In [64]:
print("\nRoll-up ke level_pendapatan:")
ru2 = cube_country.query(m_country["Avg Life Expectancy"], levels=[cube_country.levels["level_pendapatan"]])
ru2

Roll-up ke level_pendapatan:

                    Avg Life Expectancy
level_pendapatan
Aggregates                        70.74
High income                       79.15
Low income                        61.41
Lower middle income               67.20
Unknown                           68.93
Upper middle income               72.93

In [65]:
print("Slice data 2020:")
sl = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["negara"], cube_death.levels["penyebab_kematian"]],
    filter=(cube_death.levels["tahun"] == "2020")
).sort_values("Total Deaths", ascending=False).head(10)
sl

Slice data 2020:

                                            Total Deaths
negara                   penyebab_kematian
Turks and Caicos Islands All causes              3383729
Brazil                   All causes              1556824
Georgia                  All causes              1372755
United Kingdom           All causes              1069958
Gibraltar                All causes               985572
Italy                    All causes               746324
Turkmenistan             All causes               688806
France                   All causes               672827
Ukraine                  All causes               607099
Korea, Rep.              All causes               509048

In [66]:
print("Dice 2020 Indonesia:")
dc = cube_death.query(
    m_death["Total Deaths"],
    levels=[cube_death.levels["penyebab_kematian"], cube_death.levels["kelompok_umur"]],
    filter=(cube_death.levels["tahun"] == "2020")
        & (cube_death.levels["negara"] == "Indonesia")
        & (cube_death.levels["jenis_kelamin"] == "Laki-laki")
).sort_values("Total Deaths", ascending=False)
print(dc.to_string())

Dice 2020 Indonesia:
Empty DataFrame
Columns: [Total Deaths]
Index: []

## Visualisasi

In [67]:
session.url

'http://localhost:55522'

## Benchmark

In [68]:
import psycopg2, time
conn = psycopg2.connect(
    host=DB_CONFIG['host'], port=DB_CONFIG['port'],
    dbname=DB_CONFIG['dbname'], user=DB_CONFIG['user'],
    password=DB_CONFIG['password']
)
conn.autocommit = True
cur = conn.cursor()

print('Benchmark:')

start = time.time()
cur.execute("SELECT SUM(jumlah_kematian) FROM FactDeath;")
full = cur.fetchone()[0]
t_full = time.time() - start
print(f'  Full scan (semua partisi): {t_full:.5f}s -> {full}')

start = time.time()
cur.execute("SELECT SUM(jumlah_kematian) FROM FactDeath WHERE tahun = 2017;")
part = cur.fetchone()[0]
t_part = time.time() - start
print(f'  Partition pruning (tahun=2017): {t_part:.5f}s -> {part}')

ratio = round(t_full / t_part, 2) if t_part else float('inf')
print(f'  Speedup: {ratio}x')
results = [('Partition Pruning vs Full Scan', t_full, t_part, ratio)]

Benchmark:
  Full scan (semua partisi): 1.63100s -> 158764225
  Partition pruning (tahun=2017): 0.06332s -> 41261743
  Speedup: 25.76x

In [69]:
print('\nBenchmark MV:')

start = time.time()
cur.execute("""
    SELECT c.negara, SUM(fd.jumlah_kematian)
    FROM FactDeath fd
    JOIN DimCountry c ON c.country_id = fd.country_id
    GROUP BY c.negara
""")
live = cur.fetchall()
t_live = time.time() - start
print(f'  Live JOIN + GROUP BY: {t_live:.5f}s')

start = time.time()
cur.execute("SELECT * FROM mv_deaths_by_country_year;")
mv = cur.fetchall()
t_mv = time.time() - start
print(f'  Materialized View: {t_mv:.5f}s')

ratio = round(t_live / t_mv, 2) if t_mv else float('inf')
print(f'  Speedup: {ratio}x')
results.append(('Materialized View vs Live JOIN', t_live, t_mv, ratio))

Benchmark MV:
  Live JOIN + GROUP BY: 0.25702s
  Materialized View: 0.08148s
  Speedup: 3.15x

In [70]:
print('\nRingkasan:')
print(f"{'Skenario':<30} {'Full scan (s)':<15} {'Optimasi (s)':<15} {'Speedup':<10}")
for skenario, before, after, speedup in results:
    print(f"{skenario:<30} {before:<15.5f} {after:<15.5f} {speedup}x")
cur.close()
conn.close()

Ringkasan:
Skenario                       Full scan (s)   Optimasi (s)    Speedup
Partition Pruning vs Full Scan 1.63100         0.06332         25.76x
Materialized View vs Live JOIN 0.25702         0.08148         3.15x

In [76]:
list(cube_death.hierarchies)

[('country', 'kode_negara'),
 ('country', 'negara'),
 ('death', 'cause_id'),
 ('death', 'fact_death_id'),
 ('death', 'country_id'),
 ('death', 'year_id'),
 ('death', 'age_group_id'),
 ('death', 'sex_id'),
 ('year', 'tahun'),
 ('sex', 'jenis_kelamin'),
 ('cause', 'penyebab_kematian'),
 ('age', 'kelompok_umur')]

In [ ]:
negara_terbanyak = cube_death.query(
    m_death['Total Deaths'],
    levels=[cube_death.levels['negara']]
).sort_values(by='Total Deaths',ascending=False).head(10)

negara_terbanyak

                          Total Deaths
negara
Turks and Caicos Islands      23773640
Russian Federation            15930711
Georgia                       10913235
Brazil                        10786470
Gibraltar                      7623957
United Kingdom                 6206431
Italy                          5496957
Turkiye                        5145866
France                         5068261
Turkmenistan                   4977130

In [104]:
list(cube_death.hierarchies)

[('country', 'kode_negara'),
 ('country', 'negara'),
 ('death', 'cause_id'),
 ('death', 'fact_death_id'),
 ('death', 'country_id'),
 ('death', 'year_id'),
 ('death', 'age_group_id'),
 ('death', 'sex_id'),
 ('year', 'tahun'),
 ('sex', 'jenis_kelamin'),
 ('cause', 'penyebab_kematian'),
 ('age', 'kelompok_umur')]

In [87]:
pengaruh_income_level = cube_country.query(
    m_country['Avg Life Expectancy'], m_country['Avg Mortality Rate'],
    levels = [cube_country.levels['level_pendapatan'] ],
)

pengaruh_income_level

                    Avg Life Expectancy Avg Mortality Rate
level_pendapatan
Aggregates                        70.74              27.68
High income                       79.15               5.82
Low income                        61.41              51.25
Lower middle income               67.20              32.11
Unknown                           68.93              31.41
Upper middle income               72.93              15.32

In [90]:
penyakit_terbanyak = cube_death.query(
    m_death['Total Deaths'],
    levels = [cube_death.levels['penyebab_kematian']]
).sort_values(by = 'Total Deaths', ascending = False).head(10)

penyakit_terbanyak

                                                    Total Deaths
penyebab_kematian
All causes                                              74805769
Diseases of the circulatory system                       3727946
Acute myocardial infarction, unspecified                 2865571
Malignant neoplasm: Bronchus or lung, unspecified        2372311
Ischaemic heart diseases                                 2160763
Pneumonia, unspecified                                   1758319
Atherosclerotic heart disease                            1538863
Unspecified dementia                                     1490950
Other ill-defined and unspecified causes of mor...       1460058
COVID-19, virus identified                               1417801

In [92]:
list(cube_country.measures)

['Avg GDP per Capita',
 'Avg Life Expectancy',
 'Avg Mortality Rate',
 'Total Population',
 'contributors.COUNT',
 'gdp_per_capita.MEAN',
 'gdp_per_capita.SUM',
 'life_expectancy.MEAN',
 'life_expectancy.SUM',
 'mortality_rate.MEAN',
 'mortality_rate.SUM',
 'population.MEAN',
 'population.SUM',
 'update.TIMESTAMP']

In [99]:
angka_harapanhidup_angka_kematian = cube_country.query(
    m_country['Avg Life Expectancy'],m_country['Avg Mortality Rate'],
    levels = [cube_country.levels['negara']]
).sort_values(by = 'Avg Mortality Rate', ascending = False).head(10)

angka_harapanhidup_angka_kematian

                          Avg Life Expectancy  Avg Mortality Rate
negara
South Sudan                          50.75825              104.55
Central African Republic              44.9135              91.475
Somalia, Fed. Rep.                   55.32525              82.375
Niger                                 59.8025               69.25
Nigeria                              52.78675                68.9
Guinea                               59.12175               67.45
Chad                                 52.59925               65.55
Sierra Leone                         59.02675              65.225
Lesotho                               54.7235                64.7
Liberia                              61.06875               63.45

In [100]:
jenis_kelamin = cube_death.query(
    m_death['Total Deaths'],
    levels = [cube_death.levels['jenis_kelamin']]
)
jenis_kelamin

              Total Deaths
jenis_kelamin
Unknown             33,740
pria            80,826,227
wanita          74,721,492

In [103]:
kelompok_umur =cube_death.query(
    m_death['Total Deaths'],
    levels = [cube_death.levels['kelompok_umur']]
).sort_values(by='Total Deaths', ascending=False)

kelompok_umur

                                       Total Deaths
kelompok_umur
0-95+ tahun (Sangat Mendetail)            124895827
0-85+ tahun (Sangat Mendetail)             21796451
0-85+ tahun (Mendetail)                     8468730
0-75+ tahun (Cukup Mendetail)                292497
Semua usia (Paling Tidak Mendetail)          115943
0-65+ tahun (Sangat Kurang Mendetail)          6543
0-75+ tahun (Mendetail)                        5468

In [112]:
tren_kematian = cube_death.query(
    m_death['Total Deaths'],
    levels = [cube_death.levels['tahun']]
)
tren_kematian

      Total Deaths
tahun
2017    40,608,571
2018    40,354,548
2019    40,548,345
2020    34,069,995

In [ ]:
indonesia = cube_country.query(
    m_country['gdp_per_capita.MEAN'],
    levels= [cube_country.levels['negara'],cube_country.levels['tahun']],
    filter = (cube_country.levels['negara']=='Indonesia')
        &(cube_country.levels['tahun']==2017)

)
indonesia

                gdp_per_capita.MEAN
negara    tahun
Indonesia 2017             3,798.88
          2018             3,860.95
          2019             4,106.95
          2020             3,853.70